### ISSUE TITLE
Open latest wallet address on search button click, just like the old one.

### ISSUE THREAD

**Issue by evangunawan** [flexpool/frontend#120]
Loved the old one where we can get inside our mining wallet dashboard without hassle.
Or simply just set the latest value on input component?

**Comment by evangunawan** [comment]
Submitted a pull request, https://github.com/flexpool/frontend/pull/123.

Hope it helps improving the page.
PS: I am new into contributing publicly ;) thanks for reviewing.

**Comment by march08** [comment]
hey @evangunawan thanks for the PR! i've added a comment in #123 , you can check that out
