### ISSUE TITLE
Show next block share percentage and coin's exchange on miner's dashboard?

### ISSUE THREAD

**Issue by evangunawan** [flexpool/frontend#134]
Can it has more information such as next block share percentage, like in the old site,
and I think current coin's exchange rate would be good if added.

I don't have any idea where to put those information, as we already got a good looking compact UI.

Thank you.

**Comment by evangunawan** [comment]
Ah yes that's the one. My bad I didn't search them thoroughly.
I think the only consideration now is the exchange rate?

thank you!

**Comment by march08** [comment]
@evangunawan i've created a separate task for that, thanks
