### ISSUE TITLE
Hashrate Tooltip For Various Time Periods

### ISSUE THREAD

**Issue by Tigggger** [flexpool/frontend#139]
On the old site there was a tooltip for the 6h and 12 hour average effective.

Would be nice to have this on the new site, and if possible to expand it to show 3,6,12,24 hours averages

![flex](https://user-images.githubusercontent.com/3310734/115566329-111e2a00-a2b2-11eb-8e14-9e325422e298.jpg)

**Comment by AlexSSD7** [comment]
Good idea. That data can be extracted from the chart.
