### ISSUE TITLE
Past Earnings in Rewards Tab does not show accurate data?

### ISSUE THREAD

**Issue by evangunawan** [flexpool/frontend#142]
![image](https://user-images.githubusercontent.com/29895822/115594319-c9be8a80-a2ff-11eb-9f5a-4952597241b5.png)
I have 0.058 ETH in my unpaid balance (And yes, I joined the pool 5 days ago 😂).
Should the "weekly" and "monthly" is 0.058, instead of 0.047 ? 
Daily data seems accurate.

And should the labels be "this day/today", "this week", and "this month" instead of those labels (it suits for forecasted earnings)?

Thank you. I can help fix and post a PR when I have time later 😉.

**Comment by march08** [comment]
@evangunawan reading this I can agree that the wording may be a little bit confusing
The data doesn't include "today" meaning you might have earned 0.0011 today

Proposed wording:
Yesterday
Last week
Last month

cc @AlexSSD7

**Comment by evangunawan** [comment]
Ah I see. Thought today rewards was included..
Maybe we can add tooltips or some hints for the information there.

I can try and help with that if I have some free time later tomorrow. Thanks!

**Comment by AlexSSD7** [comment]
```
Yesterday
Last week
Last month
```
This will work well, I think.
