### ISSUE TITLE
FAQ page needs to have more questions

### ISSUE THREAD

**Issue by AlexSSD7** [flexpool/frontend#243]
I think that the FAQ page needs to have more questions.

![image](https://user-images.githubusercontent.com/43043344/120081287-3d9d4100-c0bd-11eb-9a5d-a324dfd16d16.png)

**Comment by indyramp** [comment]
There are a lot of new FAQs on https://www.reddit.com/r/Flexpool/comments/ornbop/nineteen_questions_and_21_answers_for_flexpool/ that could be repurposed into the site FAQ.

**Comment by AlexSSD7** [comment]
Good idea

**Comment by AlexSSD7** [comment]
Also, it would be nice to keep the coin switcher and keep FAQs per coin. @indyramp has a great FAQ here: https://www.reddit.com/r/Flexpool/comments/ornbop/nineteen_questions_and_21_answers_for_flexpool/. Might be worth copy-pasting all his stuff to the website.
