### ISSUE TITLE
Blocks chart weird behavior

### ISSUE THREAD

**Issue by AlexSSD7** [flexpool/frontend#255]
![](https://cdn.discordapp.com/attachments/761212311049994267/848881530787987456/unknown.png)

**Comment by igoralebar** [comment]
probably has something to do with clip-path 176
the missing part appears, the only problem becomes width
![SV6njumvYl](https://user-images.githubusercontent.com/78835491/121752855-c4203c80-cb19-11eb-9231-44deb341d827.gif)

**Comment by igoralebar** [comment]
User page shares chart cuts off just the same, but the cat is smaller, relative to bar width
![0WUjAXCU5h](https://user-images.githubusercontent.com/78835491/121825303-4182b300-ccba-11eb-8171-7d67c8accd0e.gif)
