### ISSUE TITLE
Change PPLNS queue length in FAQ to 1M

### ISSUE THREAD

**Issue by indyramp** [flexpool/frontend#346]
The FAQ currently shows a PPLNS queue length/depth of 6 million shares. The dashboard shows the correct(?) number of 1 million. We should sync the FAQ, since at least half a dozen people have asked this month. 

![image](https://user-images.githubusercontent.com/78050405/127729651-a83603f6-0500-466f-94ed-a23f29d61cd4.png)

There was also at least one suggestion that we either give a brief explanation of PPLNS vs PPS, or maybe link to Alex's Medium post (https://medium.com/flexpool/the-pplns-reward-system-cbe6cd1b97ed), to explain that.

**Comment by AlexSSD7** [comment]
I'd suggest saying that they can find the up to date information in the advanced PPLNS statistics under the rewards tab

**Comment by indyramp** [comment]
It would still be good to update the FAQ, as we've gotten several complaints about it in the last week.

**Comment by aminick** [comment]
FAQ has updated. Thus closing this issue.
