### ISSUE TITLE
Mined/Farmed blocks Statistics do not render correctly on refresh

### ISSUE THREAD

**Issue by E1uSiV3** [flexpool/frontend#357]
On the Mined Blocks page of the website, the "AVERAGE LUCK", "CURRENT LUCK", "NETWORK SPACE", and "NETWORK DIFFICULTY" headings do not render correctly when you refresh the page.

1. Go to "https://www.flexpool.io/blocks".
2. Refresh the page using your browsers controls (F5 or the refresh icon in Chromium based browsers).
3. When the page refreshes, the four headings show blank boxes instead of values .

**Expected behavior**
The four headings should show updated values.

**Screenshots**
Initial Page Load:
![image](https://user-images.githubusercontent.com/46492644/128013659-de1cfbd7-3e17-422b-aef0-6379d6726460.png)

After Refresh:
![image](https://user-images.githubusercontent.com/46492644/128013847-a1cf0c48-017f-4fcc-b0a7-09848f57fb6f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 20H2
 - Browser: Chrome 92.0.4515.107 (Official Build) (64-bit)
 - Browser: Brave 1.27.109 Chromium: 92.0.4515.115 (Official Build) (64-bit)
 - Browser: Edge Version 92.0.902.62 (Official build) (64-bit)

I checked behaviour for both Ethereum and Chia selected, with the same results. I also checked different languages and currencies, with the same results.

**Comment by AlexSSD7** [comment]
Looks like this already was fixed by https://github.com/flexpool/frontend/pull/355. It is just not in production yet because of some bugs the fixes has introduced.

Can you please confirm that it is working as expected here: https://frontend-git-bugfix-next-refactor-cleanup-flexpool.vercel.app ?
