### ISSUE TITLE
Network space is Undefined for "Chia" while loading the data

### ISSUE THREAD

**Issue by ariannargesi** [flexpool/frontend#382]
**How to simulate the issue?**
1- Go to /blocks
2- Select Chia from the dropdown at the top right
You can see the NETWORK SPACE box show's undefined for a few milliseconds (while loading data)
![Capture](https://user-images.githubusercontent.com/46089900/130263102-f1031915-3dad-433a-abe9-67c464129e2c.PNG)

Update
The issue is that your useLocalizedSiFormatter function at src>utils> si.utils.ts can't handle numbers with this format "5.549564940003413e+29", But it works properly with Integers

**Comment by aminick** [comment]
@ariannargesi Thanks for reporting this. I've provided a simple fix in the PR. Will publish in the next release.
