### ISSUE TITLE
Cached stats stick when searching a new miner address on the dashboard

### ISSUE THREAD

**Issue by indyramp** [flexpool/frontend#403]
**Describe the bug**
In many cases, when searching a new miner address on an already-loaded dashboard, the old address's details remain until a force reload (ctrl+f5). 

**To Reproduce**
1. Search a wallet address or load a bookmarked dashboard. 
2. Wait for stats to display
3. Search a different address (same coin) in the search box at the top
4. See same stats from previous miner address
5. Press Ctrl+F5
6. See stats from new address

**Expected behavior**
When searching for a given wallet address, it should show that address's stats on first load. 

**Desktop (please complete the following information):**
 - Windows 10 current patch level, Google Chrome Version 92.0.4515.159 (Official Build) (64-bit)
 - Windows 10 current patch level, Microsoft Edge (chromium version) Version 92.0.902.78 (Official build) (64-bit)

**Additional context**
For clearest validation, use one of our top miners for one of the addresses in reproduction steps.

**Comment by AlexSSD7** [comment]
@aminick Workers don't seem to be updating.
