### ISSUE TITLE
Horizontal scroll bar in blocks list when round time string is too long

### ISSUE THREAD

**Issue by igoralebar** [flexpool/frontend#42]
![bmjUwbDCSZ](https://user-images.githubusercontent.com/78835491/114501221-3e276880-9c32-11eb-9df1-0dc2f02975c4.gif)

**Comment by AlexSSD7** [comment]
I think the round time can ba shortened in this way: `1 h, 11m, 20s`

**Comment by march08** [comment]
Suggested shortening requires creating a new locale which is not very scalable, see the solution in #80
