### ISSUE TITLE
Chia's payments graph only shows the first payment for any specific day

### ISSUE THREAD

**Issue by aminick** [flexpool/frontend#420]
![image](https://user-images.githubusercontent.com/5182324/131665268-fb212d09-ba18-4099-a320-6d94e500983d.png)

![image](https://user-images.githubusercontent.com/5182324/131665287-27aed87f-96ab-4b60-b2c8-ce34abd631c3.png)

As we can see in the above example, the graph does not aggregate all payments for the entire day.

**Comment by f7byu3e4jn** [comment]
I’m having the same issue. I  mentioned this a few times on the discord for the last few weeks, but the error is still there. It should be pretty easy to solve, as all other bar graphs (e.g. chia rewards) do accumulate daily values without issues.
