### ISSUE TITLE
flexfarmer get-started page missing link to other get-started page

### ISSUE THREAD

**Issue by indyramp** [flexpool/frontend#430]
Someone on reddit just comment on this line on https://www.flexpool.io/get-started/xch/flexfarmer/

PlotNFT joined to Flexpool (see getting started for instructions).

That should point people at the main Chia get-started page since the regular chia client is required for the plotnft part of the process. 

Let's add something like:

If you need to set up the Chia client to manage your PlotNFT, see our _CLI_ and _GUI_ instructions for getting started with the official Chia client. 

CLI link: https://www.flexpool.io/get-started/xch/XCH-CLI/
GUI link: https://www.flexpool.io/get-started/xch/XCH-GUI/

**Comment by indyramp** [comment]
One more request on this section - I'll put a new issue in if requested. 

< Raspberry Pi is also supported
> Raspberry Pi is also supported with a 64-bit OS (Raspberry Pi 3b+ or newer) or 64-bit emulation with QEMU (some older Raspberry Pi models, not recommended)

**Comment by AlexSSD7** [comment]
FYI next FlexFarmer release will have native 32-bit builds, so no more QEMU 64-bit emulation.
