### ISSUE TITLE
Show gas limit on miner details

### ISSUE THREAD

**Issue by march08** [flexpool/frontend#44]
![Screen Shot 2021-04-13 at 8 28 44](https://user-images.githubusercontent.com/15802823/114506559-44b5e000-9c32-11eb-9412-b771caf84b27.png)

**Comment by 0ze** [comment]
also show current gas for reference as well

**Comment by AlexSSD7** [comment]
> also show current gas for reference as well

Not sure if it is necessary. This will also require some work on the API.

**Comment by ANSN1** [comment]
Opened [https://github.com/flexpool/frontend/pull/109](https://github.com/flexpool/frontend/pull/109)
