### ISSUE TITLE
Suggestion to call out unconfirmed rewards on top stats row

### ISSUE THREAD

**Issue by indyramp** [flexpool/frontend#441]
A miner on Telegram suggested adding unconfirmed rewards to the top row of stats alongside the unpaid balance. 

Something like:

![image](https://user-images.githubusercontent.com/78050405/133836748-883d1d96-c52e-44f6-a049-5a78040d4454.png)

Maybe shorten the text with a tooltip, but most miners don't seem to bother with tooltips. 

![image](https://user-images.githubusercontent.com/78050405/133836844-2c344540-6073-4328-af1e-64be1f1aab8f.png)

**Comment by AlexSSD7** [comment]
That would clutter the UI without the practical use for 99.9% of our users.
