### ISSUE TITLE
Clicking 'worker' results in bad URI

### ISSUE THREAD

**Issue by aminick** [flexpool/frontend#457]
![image](https://user-images.githubusercontent.com/5182324/135111649-f65c1879-7bcd-4c7f-be34-cbb341bd1338.png)

**Comment by indyramp** [comment]
Looks like this can be easily reproduced.

Load a current dashboard (i.e. https://www.flexpool.io/miner/eth/0x2911BF64F264d0737E01B3183d1BE1fD792471bF )

Click on a miner to view miner stats. 

F5 or otherwise refresh the browser. 

"Can't find the moon."
