### ISSUE TITLE
Dynamic manifest for miner page

### ISSUE THREAD

**Issue by march08** [flexpool/frontend#56]
generating dynamic manifest with `start_url: /miner/{coin}/{address}` allows PWA to open the app saved as desktop shortcut on the miners page

When saved as a desktop shortcut/app (PWA), it allows the app to redirect to the miners page. This is not such an issue with android as it uses redirect to an URL from which the app was installed (triggered on window event `appinstalled`) rather iOS improvement.

**Comment by AlexSSD7** [comment]
Hasn't this been fixed with the PWA PR? @march08

**Comment by march08** [comment]
@AlexSSD7 unfortunately ios doesn't support some advanced features so this is still required :/
