### ISSUE TITLE
Blocks Mined Text does not line up with actual

### ISSUE THREAD

**Issue by dompazz** [flexpool/frontend#65]
**Describe the bug**
Site announces, "You haven't mined any block yet." when there are blocks mined.

**To Reproduce**
https://beta.flexpool.io/miner/eth/0x25AEA118f3FFc42FCE64a33e6ba9D92bB990d22c/blocks

**Screenshots**
![image](https://user-images.githubusercontent.com/5799952/114621628-ecef9700-9c7a-11eb-8f51-82e30968c924.png)

**Desktop (please complete the following information):**
 - Ubuntu 20.04
 - Firefox 87.0 (64bit)

**Comment by march08** [comment]
duplicate #57
