### ISSUE TITLE
Change Port

### ISSUE THREAD

**Issue by edcomrocha** [flexpool/frontend#674]
How to change the frontend to run on port 81 or 82?
I have tried and I get the error:

`$ next dev
Error: listen EACCES: permission denied 0.0.0.0:81
    at Server.setupListenHandle [as _listen2] (net.js:1314:21)
    at listenInCluster (net.js:1379:12)
    at Server.listen (net.js:1465:7)
    at /home/edvaldo/frontend/node_modules/next/dist/server/lib/start-server.js:45:16
    at new Promise (<anonymous>)
    at Object.startServer (/home/edvaldo/frontend/node_modules/next/dist/server/lib/start-server.js:19:12)
    at nextDev (/home/edvaldo/frontend/node_modules/next/dist/cli/next-dev.js:116:23)
    at /home/edvaldo/frontend/node_modules/next/dist/bin/next:130:34 {
  code: 'EACCES',
  errno: -13,
  syscall: 'listen',
  address: '0.0.0.0',
  port: 81
}
error Command failed with exit code 1.
`

Thanks for all the help

Hugs

**Comment by AlexSSD7** [comment]
You should *not* run next dev with 80/81/82/80whatever port. You should use 3000 (this is the default).

**EDIT:** That seems to be an [XY problem](https://xyproblem.info/), why would you need to run the website locally?

**Comment by edcomrocha** [comment]
Okay, I really didn't explain correctly.
Sorry I'm new at this (very much).

I'm going to use port 3000 in another daemon (Blinkhash foundation-server) it gives me apis's on that port.

So that's why I want to change the port to 81 and later to 80 to run on a site (modifying the layout to my liking) like yours.

I would like to run this frontend to get this information from my api, modify the frontend layout and run in the application I mentioned.
Sorry if I can't express myself correctly, I'm not very good with words.

Thanks for the answer.

Hugs!!

**Comment by aminick** [comment]
@edcomrocha just do `yarn dev -p 3001` and you are good to go at port 3001
