### ISSUE TITLE
Update FAQ "lost keys" for ETH for the end of mining

### ISSUE THREAD

**Issue by indyramp** [flexpool/frontend#700]
Current text:

I've lost my keys/mnemonics or my exchange has shut down my account. How can I get my unpaid balance?

First, stop mining to a wallet if you no longer believe you can access it. Then, contact support with a description of the situation and your ETH address. They will let you know if anything can be done.

New text

**If you are unable to sign an Ethereum digital message with your keys or mnemonics, we cannot transfer an ETH balance, as there is no longer any way to verify new mining since mining has ended. 

If you have your keys or mnemonics but they have been compromised, you can sign an Ethereum digital message. Contact support for instructions before doing so.**

**Comment by aminick** [comment]
Closed as users can no longer view ETH faqs
